version: 0.1
env:
  variables:
    APP_NAME: "logic-consumer-web"
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo install process started
      - npm install -g @angular/cli
      - npm install

  build:
    commands:
      - echo build process started now
      - ng build --prod
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - cd dist/logic-consumer-web
